### ISSUE TITLE
Missing (?) elements in LIST entries

### ISSUE THREAD

**Issue by ziegm** [ahdis/ch-emed-pmp#42]
[1-3-MTP-Temesta](http://build.fhir.org/ig/ahdis/ch-emed-pmp/Bundle-1-3-MTPTemesta.json.html)
[2-1-PADV-Temesta](http://build.fhir.org/ig/ahdis/ch-emed-pmp/Bundle-2-1-PADVTemesta.json.html): stopped
[LIST](https://github.com/ahdis/hci-analyzer/blob/master/input/resources/parameters/PMP2-List.json)

I am currently reworking the HCI Analyzer use cases, where the PMP list is taken as input document. I noticed that the following information is missing in the list:

HCI Use Case:
* MedStat/Obs: extension with reference to the parent document

General:
* Obs: the original element http://fhir.ch/ig/ch-emed/StructureDefinition/ch-emed-ext-treatmentplan is not anymore in the list-observation, so the link to the MTP get lost. Is there a reason for this behaviour?

**Comment by qligier** [comment]
Should be fixed by https://github.com/project-husky/husky/commit/e755b192a22468adbc4747dffe3ce8a5f74f78f6.

**Comment by ziegm** [comment]
Is there a redeploy necessary or should it work already?

**Comment by qligier** [comment]
I haven't redeployed yet, I want to fix a few more things.

**Comment by ziegm** [comment]
1. still missing the parentDocument extension in each entry
2. fixed (thanks!)
